### ISSUE TITLE
スケッチのコンテンツのVgidチェック

### ISSUE THREAD

**Issue by kimhyonju** [kimhyonju/portfolio#37]
Javascriptとoptionの確認

**Comment by sakamotodesu** [comment]
指示が曖昧で何をすればいいのかわかりません。
具体的な問題点を教えてください。

**Comment by kimhyonju** [comment]
> 指示が曖昧で何をすればいいのかわかりません。
> 具体的な問題点を教えてください。

ローディングされた時、スケッチのコンテンツの要素が固まっていて時間が経ったら動くバグが発生。スケッチの要素を動かすJquaryはVgridというものです。javascriptのoptionの設定に問題がないか確認お願いします。
ちなみに給料はないです。ノーペイ。以上。

**Comment by sakamotodesu** [comment]
#38 にて修正したコードを作成したのでご確認お願い致します。
